[package]
name = "rust-tiny-rdmbs"
version = "0.1.0"
authors = ["koralle"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zerocopy = "0.4.0"
